#!/bin/bash
un=gtc_`date +%s`
#rp=/root/shared/cjzimmer-bbapi/scratch/$un
rp=/mnt/bblv_57/$un
mkdir -p $rp
cp gtc $rp
cp gtc.in $rp

pushd $rp
mkdir -p restart_dir1
mkdir -p restart_dir2

mkdir -p phi_dir
mkdir -p trackp_dir

export PFS_DIR=/root/shared/cjzimmer-bbapi/scratch/
export PERSIST_DIR=/mnt/bblv_57/$un/restart_dir2
export MANAGE_FILES=1
export OMP_NUM_THREADS=4
export LD_LIBRARY_PATH=/root/shared/cjzimmer-bbapi/gtc-support/hdf5-1.8.17/hdf5/lib/:/usr/local/lib

mpirun --allow-run-as-root -x LD_PRELOAD=/usr/local/lib/libiointercept.so -np 4 ./gtc
